# Matrix Multiplication

In [1]:
import numpy as np

In [2]:
inputs = np.random.randint(-5, 5, size=(3, 4))
weights = np.random.randint(-5, 5, size=(5, 4))
biases = [2, 5, 0.8, 2.3, 6]

In [3]:
print(inputs, weights)

[[ 3  1 -1 -2]
 [-5 -1  4 -4]
 [-5  3  0  1]] [[-5 -3 -5  4]
 [ 4 -1  2 -1]
 [-1 -5  4 -4]
 [-4  1  1  0]
 [-5  3 -5  1]]


In [4]:
outputs = np.dot(inputs, weights.T) + biases

In [5]:
print(outputs)

[[-19.   16.   -3.2  -9.7  -3. ]
 [ -6.   -2.   42.8  25.3   4. ]
 [ 22.  -19.  -13.2  25.3  41. ]]
