# Backpropagation (Full Code)

In [2]:
import numpy as np
import nnfs
from nnfs.datasets import spiral_data

In [3]:
nnfs.init()

In [5]:
%run Backpropagation_Class.ipynb

In [6]:
%run Softmax_Loss.ipynb

In [7]:
X, y = spiral_data(samples=100, classes=3)

In [8]:
dense1 = Layer_Dense(2, 3)
activation1 = Activation_ReLU()
dense2 = Layer_Dense(3, 3)
loss_activation = Activation_Softmax_Loss_CategoricalCrossentropy()

In [10]:
dense1.forward(X)
activation1.forward(dense1.outputs)
dense2.forward(activation1.output)

In [11]:
loss = loss_activation.forward(dense2.outputs, y)

In [12]:
print(loss_activation.output[:5])
print('loss:', loss)

[[0.33333334 0.33333334 0.33333334]
 [0.33333316 0.3333332  0.33333364]
 [0.33333287 0.3333329  0.33333418]
 [0.3333326  0.33333263 0.33333477]
 [0.33333233 0.3333324  0.33333528]]
loss: 1.0986104


In [13]:
predictions = np.argmax(loss_activation.output, axis=1)
if len(y.shape) == 2:
    y = np.argmax(y, axis=1)
accuracy = np.mean(predictions == y)

In [14]:
print('acc:', accuracy)

acc: 0.34


In [15]:
loss_activation.backward(loss_activation.output, y)
dense2.backward(loss_activation.dinputs)
activation1.backward(dense2.dinputs)
dense1.backward(activation1.dinputs)

In [16]:
print(dense1.dweights)
print(dense1.dbiases)
print(dense2.dweights)
print(dense2.dbiases)

[[ 1.5766358e-04  7.8368575e-05  4.7324404e-05]
 [ 1.8161036e-04  1.1045571e-05 -3.3096316e-05]]
[[-3.6055347e-04  9.6611722e-05 -1.0367142e-04]]
[[ 5.4410957e-05  1.0741142e-04 -1.6182236e-04]
 [-4.0791339e-05 -7.1678100e-05  1.1246944e-04]
 [-5.3011299e-05  8.5817286e-05 -3.2805994e-05]]
[[-1.0732794e-05 -9.4590941e-06  2.0027626e-05]]
