# Basic Backpropagation (Chain rule) 

## Multiple Neurons (Full Code)

### Batch of samples 

In [1]:
import numpy as np

In [2]:
dvalues = np.array([[1.0, 1.0, 1.0], [2.0, 2.0, 2.0], [3.0, 3.0, 3.0]])

In [3]:
inputs = np.random.randn(3, 4)
print(inputs)

[[-0.06659001  1.11261673  0.52279547  1.87151526]
 [ 1.47547598  0.10325425  0.997464   -1.17027453]
 [-3.17980051  0.65398006 -0.28901811  0.52079917]]


In [4]:
weights = np.random.randn(3, 4).T
print(weights[0])

[-0.61206289  1.19032697 -0.2982999 ]


In [5]:
biases = np.array([[2, 3, 0.5]])

#### Forward pass 

In [6]:
layer_outputs = np.dot(inputs, weights) + biases
relu_outputs = np.maximum(0, layer_outputs)

#### Backward pass

In [7]:
drelu = relu_outputs.copy()
drelu[layer_outputs <= 0] = 0

#### Derivatives

In [8]:
dinputs = np.dot(drelu, weights.T)
dweights = np.dot(inputs.T, drelu)
dbiases = np.sum(drelu, axis=0, keepdims=True)

#### Update parameters

In [9]:
weights += -0.001 * dweights
biases += -0.001 * dbiases

In [10]:
print(weights)
print(biases)

[[-0.59765453  1.18130449 -0.29925353]
 [-0.26218328 -0.53607461 -0.03115349]
 [-1.70819412  1.2706868   1.22802498]
 [ 0.42569946 -0.21581957 -0.72865013]]
[[1.99383566 2.99118026 0.49716869]]
